#!/bin/sh

apt update && apt upgrade

apt install -y vim xorg dwm xcape sudo zsh tmux git firefox-esr

while : ; do
        read -p "Do you want to install the CyperSecurity tools too? (nmap, gobuster, etc.) [Y/n]: " answer
        [ "$answer" = "" -o "$answer" = "y" -o "$answer" = "Y" -o "$answer" = "n" -o "$answer" = "N" ] && break
        echo "'$answer' is non acceptable!"
done

[ "$answer" = "" -o "$answer" = "y" -o "$answer" = "Y" ] && apt install -y nmap gobuster 

cat <<EOF > /etc/X11/xinit/xinitrc
#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

/usr/bin/setxkbmap -option ctrl:nocaps -option ctrl:swap_lalt_lctl_lwin
/usr/bin/xcape -e 'Control_L=Escape'

# invoke global X session script
. /etc/X11/Xsession
EOF

adduser --disabled-password --gecos "" buduboti
adduser buduboti sudo

su buduboti

cd $HOME

git clone https://github.com/buduboti/dotfiles .dotfiles

.dotfiles/install
