#!/bin/sh

apt update

apt install -y vim xorg dwm xcape sudo zsh tmux git

cat <<EOF > /etc/X11/xinit/xinitrc
#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

/usr/bin/setxkbmap -option ctrl:nocaps -option ctrl:swap_lalt_lctl_lwin
/usr/bin/xcape -e 'Control_L=Escape'

# invoke global X session script
. /etc/X11/Xsession
EOF

cd $HOME

git clone https://github.com/buduboti/dotfiles .dotfiles

.dotfiles/install
